/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GenerateChatSessionImport } from './routes/generate-chat-session'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const GenerateChatSessionRoute = GenerateChatSessionImport.update({
  id: '/generate-chat-session',
  path: '/generate-chat-session',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/generate-chat-session': {
      id: '/generate-chat-session'
      path: '/generate-chat-session'
      fullPath: '/generate-chat-session'
      preLoaderRoute: typeof GenerateChatSessionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-chat-session': typeof GenerateChatSessionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-chat-session': typeof GenerateChatSessionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/generate-chat-session': typeof GenerateChatSessionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate-chat-session'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate-chat-session'
  id: '__root__' | '/' | '/generate-chat-session'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateChatSessionRoute: typeof GenerateChatSessionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateChatSessionRoute: GenerateChatSessionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/generate-chat-session"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/generate-chat-session": {
      "filePath": "generate-chat-session.ts"
    }
  }
}
ROUTE_MANIFEST_END */
